# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure Web App - JavaMicro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Prepare web package
        run: |
          New-Item -ItemType Directory -Force -Path published
          Copy-Item -Path "index.html", "web.config", "package.json", "css", "js", "public" -Destination "published" -Recurse -Force
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB68325C11474514BEAFF7B574909EDA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68096458A9014B5DBD9FB20CF484F359 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_199082B306064975AAA3DAAA61D0BBC4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JavaMicro'
          slot-name: 'Production'
          package: .